version: "3.8"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=elizaaugusta71@gmail.com
    depends_on:
      - nginx-proxy
    restart: always

  portfolio:
    image: seu_usuario_dockerhub/portfolio:latest
    container_name: portfolio
    environment:
      - VIRTUAL_HOST=portfolio.dominio.com
      - LETSENCRYPT_HOST=portfolio.dominio.com
      - LETSENCRYPT_EMAIL=elizaaugusta71@gmail.com
    expose:
      - "80"
    restart: always